# Generated by Django 4.1.5 on 2023-04-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC', models.CharField(max_length=50)),
                ('Colaborador_1', models.CharField(max_length=50, verbose_name='Colaborador 1°')),
                ('Colaborador_2', models.CharField(max_length=50, verbose_name='Colaborador 2°')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('Ind', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
