# Generated by Django 4.2 on 2023-04-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='Data',
            new_name='Data_01',
        ),
    ]
