# Generated by Django 4.2 on 2023-04-18 01:03

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='Fotos',
            field=models.ImageField(null=True, upload_to=cadastros.models.upload_img_obra),
        ),
    ]
