# Generated by Django 4.2 on 2023-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC', models.CharField(max_length=100)),
                ('Escada', models.BooleanField(help_text='Escada está segura conforme treinamentos')),
                ('Tempo', models.BooleanField(help_text='Tempo está favorável para execução da atividade?')),
                ('Poste', models.BooleanField(help_text='Verificou se está energizado?')),
                ('Animais', models.BooleanField(help_text='Verificação de ambiente')),
                ('Epis', models.BooleanField(help_text='Está usando os equipamentos de segurança corretos para executa essa atividade')),
                ('Sinalizacao', models.BooleanField(help_text='Área de trabalho já está sinalizado conforme treinamento?', verbose_name='Sinalização')),
                ('Colaborador', models.CharField(max_length=100)),
                ('Ind', models.CharField(max_length=10, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='obras',
            name='Check1',
            field=models.BooleanField(verbose_name='Preenchido Check liste de seguraça'),
        ),
    ]
