# Generated by Django 4.2 on 2023-04-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0002_obras_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
            preserve_default=False,
        ),
    ]
