# Generated by Django 4.2 on 2023-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_check_list_alter_obras_check1'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_list',
            name='Check_List',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
