# Generated by Django 4.2 on 2023-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_data_obras_data_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='Data_02',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Última atualização'),
        ),
    ]
