# Generated by Django 4.2 on 2023-04-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_obras_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='usuario',
        ),
    ]
