# Generated by Django 4.2 on 2023-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_obras_data_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='Data_01',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Data da Criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obras',
            name='Data_02',
            field=models.DateTimeField(auto_now=True, default=1, verbose_name='Última atualização'),
            preserve_default=False,
        ),
    ]
