# Generated by Django 4.2 on 2023-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Coladorador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='Cor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Placa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Tipo_veiculo',
            field=models.CharField(choices=[('Particula', 'Particula'), ('Icomon', 'Icomon'), ('Parceiro', 'Parceiro')], default=1, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='veiculo',
            field=models.CharField(default=1, help_text='Modelo do veiculo', max_length=100),
            preserve_default=False,
        ),
    ]
